### ISSUE TITLE
Event ordering issue on delete

### ISSUE THREAD

**Issue by sdras** [johnpapa/vue-heroes#3]
Because the delete button is nested in the li, which adds the form when clicked on, there's a momentary display of the adding form when you're deleting. My suggestion would be to move the delete button out of clickable area, or write some logic to detect what if the user is on the delete boundingClientRect, but both are probably out of the scope of the project for now :) Let me know if you'd like a PR!

**Comment by johnpapa** [comment]
yeah, something to stop the bubbling of events would be good.

**Comment by johnpapa** [comment]
refactored. now resolved. thank you
